steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/gin-tarefas/cicd-prod', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/gin-tarefas/cicd-prod']

  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'deployment.yaml']
options:
  logging: NONE
